// <auto-generated />
namespace AdminDashboardMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class extend_application_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extend_application_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202110201346018_extend_application_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
